### PR TITLE
create sign-up page

### PR DESCRIPTION
**Pull request by agrawalshanu708**
add two section 
1. for image
2. for sign-up forrm
3.
Screenshot (92)

### CODE REVIEW

**Comment by MonikaJhingan** [comment]
The page looks good to be merged.

**Comment by Samarth-5109** [comment]
Looks good to be merged

**Review by therajatg — APPROVED** [review]
looks good

**Review by MonikaJhingan — APPROVED** [review]
Just the basic color combination needs to be improved later rest is fine.

**Pull request merged**
